---
title: "Eigendata"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Eigendata}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

This vignette shows how to compute eigendata modules and optionally feed them into downstream analyses.

## Prerequisites

```{r setup, eval=FALSE}
library(MeTime)
library(magrittr)
```

## Workflow

```{r, eval=FALSE}
# Load the imputed analyser object.
load("adni_nmr_data")
which_data <- "nmr_data"

my_analyzer <- adni_nmr_data %>%
  add_screening_vars(vars=c("APOEGrp", "DXGrp_longi", "PTGENDER", "PTEDUCAT")) %>%
  add_distribution_vars_to_rows(
    screening_vars=NULL,
    distribution_vars=c("ADNI_MEM", "ADNI_LAN", "ADNI_EF", "APOEGrp", "DXGrp_longi", "PTGENDER", "Age", "BMI", "PTEDUCAT"),
    which_data=which_data
  ) %>%
  mod_mutate(
    which_data=which_data,
    type="row_data",
    APOEGrp=as.factor(APOEGrp),
    PTGENDER=as.factor(PTGENDER),
    PTEDUCAT=as.factor(PTEDUCAT),
    DXGrp_longi=ifelse(DXGrp_longi == "CN_AD_convert", "AD_converter", DXGrp_longi),
    DXGrp_longi=ifelse(DXGrp_longi == "MCI_AD_convert", "AD_converter", DXGrp_longi)
  ) %>%
  mod_filter(
    which_data=which_data,
    type="row_data",
    !DXGrp_longi %in% c("CN_MCI_convert", "MCI_CN_revert", "mix_AD_stable", "mix_CN_stable", "mix_MCI_stable")
  ) %>%
  mod_trans_zscore(which_data=which_data) %>%
  mod_trans_eigendata(
    which_data=which_data,
    append=TRUE,
    cols_for_meta=list(biocrates_data=c(id="id", sub_pathway="Class")),
    minClusterSize=2,
    deepSplit=3,
    pamRespectsDendro=TRUE
  )

# You can later continue with any calculation here.
# For example, conservation index with eigendata:
# my_analyzer <- my_analyzer %>%
#   calc_conservation_metabolite(
#     which_data="biocrates_data_with_eigenmetabs_1",
#     stratifications=list(time=c("0", "12", "24")),
#     verbose=FALSE,
#     cols_for_meta=list(biocrates_data_with_eigen_metabs_1=c(id="id", sub_pathway="sub_pathway")),
#     name="Conservation_Metabolite"
#   ) %>%
#   calc_conservation_metabotype(
#     which_data="biocrates_data_with_eigenmetabs_1",
#     stratifications=list(time=c("0", "12", "24")),
#     verbose=FALSE,
#     cols_for_meta=c("ADNI_MEM", "ADNI_LAN", "ADNI_EF", "APOEGrp", "DXGrp_longi", "PTGENDER", "Age", "BMI"),
#     name="Conservation_Metabotype"
#   ) %>%
#   mod_generate_plots(type="CI_metabotype", results_index=3)
```
