---
title: "networks"
date: 2026-01-30
output:
 rmdformats::readthedown:
  highlight: kate
  code_folding: hide
--- 

```{css, echo=FALSE}
     #content{max-width:100%}
     #sidebar{bacgkround:black}
     #postamble{border-top:solid 10px black}
     .container{width:100%}
     .button_fun{padding: 0 2px; border:transparent; background:transparent; color:#9F2042; }
     .button_fun:hover{padding: 0 2px; border:transparent; background:transparent; color:#9F2042;font-weight:bold}
     .body_fun{border-radius: 10px; background:rgb(214, 214, 214); padding:10px; margin:10px 0;position:relative}
     .button_copy{margin:10px;padding:5px;border-radius:5px;background:white;color:#9F2042;border-color:transparent;position:absolute;top:0;right:0}
     .button_copy:hover{margin:10px;padding:5px;background:#9F2042;color:white;}
```


# genenet_ggm_results

## Analyzer info
```{r,echo=F, warning=FALSE, message=FALSE}
results <- analyzer_list[[1]]@results
 print(analyzer_list[[1]])
```


```{r, echo=F}
## Pipe information
htmltools::HTML("<div class=body_fun> object %>% <br><button class=button_copy onclick='copyToClipboard()'>Copy to Clipboard</button>
                      <script>
 function copyToClipboard() {var text = 'mod_trans_log(which_data = 'biocrates_data',base = 2) %>% <br>mod_impute(which_data = 'biocrates_data',method = 'rf') %>% <br>mod_trans_log(which_data = 'lipid_data',base = 2) %>% <br>add_distribution_vars_to_rows(screening_vars = NULL,distribution_vars = c('APOEGrp', 'PTGENDER', 'Age', 'BMI', 'PTEDUCAT', 'DXGrp_long'),which_data = 'biocrates_data') %>% <br>mod_merge_row_data_and_data(which_data = 'biocrates_data',mutations = list(data = NULL, row_data = c('APOEGrp', 'PTGENDER', 'Age', 'BMI', 'PTEDUCAT', 'TOTAL_C', 'HDL_C')),name = 'ggm_data') %>% <br>mod_mutate(which_data = 'ggm_data',type = 'data',mutations = 'APOEGrp=as.numeric, PTGENDER=APOEGrp, PTEDUCAT=as.numeric, APOEGrp=PTGENDER, PTGENDER=as.numeric, PTEDUCAT=PTEDUCAT') %>% <br>calc_ggm_genenet(which_data = 'ggm_data',threshold = 'li',all = FALSE,cols_for_meta = list(biocrates_data = c(sub_pathway = 'Class')),covariates = c('Age', 'BMI', 'APOEGrp', 'PTGENDER', 'PTEDUCAT', 'TOTAL_C', 'HDL_C'),stratifications = list(time = c('t0', 't12', 't24')),name = 'genenet_ggm_results')  <br>';
var tempInput = document.createElement('input');
            tempInput.value = text;
            document.body.appendChild(tempInput);
            tempInput.select();
            document.execCommand('copy');
            document.body.removeChild(tempInput);
    }

  </script>
<div style= margin-left:5px>   <button class=button_fun data-toggle=modal data-target=#11 >mod_trans_log</button><span>(which_data = 'biocrates_data',base = 2) %>% </span><br>   <button class=button_fun data-toggle=modal data-target=#12 >mod_impute</button><span>(which_data = 'biocrates_data',method = 'rf') %>% </span><br>   <button class=button_fun data-toggle=modal data-target=#13 >mod_trans_log</button><span>(which_data = 'lipid_data',base = 2) %>% </span><br>   <button class=button_fun data-toggle=modal data-target=#14 >add_distribution_vars_to_rows</button><span>(screening_vars = NULL,distribution_vars = c('APOEGrp', 'PTGENDER', 'Age', 'BMI', 'PTEDUCAT', 'DXGrp_long'),which_data = 'biocrates_data') %>% </span><br>   <button class=button_fun data-toggle=modal data-target=#15 >mod_merge_row_data_and_data</button><span>(which_data = 'biocrates_data',mutations = list(data = NULL, row_data = c('APOEGrp', 'PTGENDER', 'Age', 'BMI', 'PTEDUCAT', 'TOTAL_C', 'HDL_C')),name = 'ggm_data') %>% </span><br>   <button class=button_fun data-toggle=modal data-target=#16 >mod_mutate</button><span>(which_data = 'ggm_data',type = 'data',mutations = 'APOEGrp=as.numeric, PTGENDER=APOEGrp, PTEDUCAT=as.numeric, APOEGrp=PTGENDER, PTGENDER=as.numeric, PTEDUCAT=PTEDUCAT') %>% </span><br>   <button class=button_fun data-toggle=modal data-target=#17 >calc_ggm_genenet</button><span>(which_data = 'ggm_data',threshold = 'li',all = FALSE,cols_for_meta = list(biocrates_data = c(sub_pathway = 'Class')),covariates = c('Age', 'BMI', 'APOEGrp', 'PTGENDER', 'PTEDUCAT', 'TOTAL_C', 'HDL_C'),stratifications = list(time = c('t0', 't12', 't24')),name = 'genenet_ggm_results')  </span><br></div></div>")
```

```{r ,echo=F}
bsplus::bs_modal(id = "11",title = "mod_trans_log",size = "large",body = "_F_u_n_c_t_i_o_n _t_o _a_p_p_l_y _l_o_g _t_r_a_n_s_f_o_r_m_a_t_i_o_n\\n\\n_D_e_s_c_r_i_p_t_i_o_n:\\n\\n     Modification(mod) function to log transform dataset/s\\n\\n_U_s_a_g_e:\\n\\n     \\n         (object, which_data, base)\\n     \\n_A_r_g_u_m_e_n_t_s:\\n\\n  object: An object of class metime_analyser\\n\\nwhich_data: Name/s of the dataset to be used\\n\\n    base: base of logarithm to be used\\n\\n_V_a_l_u_e:\\n\\n     An object of class metime_analyser with log-transformed dataset/s\\n\\n_S_e_e _A_l_s_o:\\n\\n     base::log, mod_trans_zscore\\n\\n_E_x_a_m_p_l_e_s:\\n\\n     # example to apply log transformation\\n     object <- mod_logtrans(object, which_data='name of the dataset', base=2)\\n     ")
``` 

```{r ,echo=F}
bsplus::bs_modal(id = "12",title = "mod_impute",size = "large",body = "_I_m_p_u_t_a_t_i_o_n _o_f _m_i_s_s_i_n_g _v_a_l_u_e_s\\n\\n_D_e_s_c_r_i_p_t_i_o_n:\\n\\n     This function imputes missing values using one of the implemented\\n     imputation methods.\\n\\n_U_s_a_g_e:\\n\\n     \\n         (\\n       object,\\n       which_data,\\n       method = 'rf',\\n       thresh = 0.3,\\n       path_to_diagnostics = NULL\\n     )\\n     \\n_A_r_g_u_m_e_n_t_s:\\n\\n  object: a S4 object of class 'metime_analyser'.\\n\\nwhich_data: a character defining which dataset should be imputed.\\n\\n  method: a character defining the method for imputation. See details\\n          for more information. Default set to 'rf'\\n\\n  thresh: a numeric defining at which missingness level metabolites\\n          will be excluded. Default set to 0.3 (30% missingness)\\n\\npath_to_diagnostics: a character defining the path to where a\\n          diagnostic file is being written.\\n\\n_D_e_t_a_i_l_s:\\n\\n     additional methods are currently not implemented such as knn, pmm,\\n     norm etc.\\n\\n_V_a_l_u_e:\\n\\n     S4 object of the class 'metime_analyser' with mutated col_data and\\n     row_data.\\n")
``` 

```{r ,echo=F}
bsplus::bs_modal(id = "13",title = "mod_trans_log",size = "large",body = "_F_u_n_c_t_i_o_n _t_o _a_p_p_l_y _l_o_g _t_r_a_n_s_f_o_r_m_a_t_i_o_n\\n\\n_D_e_s_c_r_i_p_t_i_o_n:\\n\\n     Modification(mod) function to log transform dataset/s\\n\\n_U_s_a_g_e:\\n\\n     \\n         (object, which_data, base)\\n     \\n_A_r_g_u_m_e_n_t_s:\\n\\n  object: An object of class metime_analyser\\n\\nwhich_data: Name/s of the dataset to be used\\n\\n    base: base of logarithm to be used\\n\\n_V_a_l_u_e:\\n\\n     An object of class metime_analyser with log-transformed dataset/s\\n\\n_S_e_e _A_l_s_o:\\n\\n     base::log, mod_trans_zscore\\n\\n_E_x_a_m_p_l_e_s:\\n\\n     # example to apply log transformation\\n     object <- mod_logtrans(object, which_data='name of the dataset', base=2)\\n     ")
``` 

```{r ,echo=F}
bsplus::bs_modal(id = "14",title = "add_distribution_vars_to_rows",size = "large",body = "_A_d_d _p_h_e_n_o_t_y_p_i_c _m_e_a_s_u_r_e_m_e_n_t_s _t_h_a_t _a_r_e _n_o_t _a_d_d_e_d _t_o _t_h_e _r_o_w__d_a_t_a _o_f _t_h_e\\n_d_a_t_a_s_e_t\\n\\n_D_e_s_c_r_i_p_t_i_o_n:\\n\\n     A method applied on the s4 object of class 'metime_analyser' to\\n     add all those datapoints that are present in phenotype dataframe\\n     but not in row_data comes with the feature of updating those data\\n     points measured only at screening to all datapoints and then\\n     adding it to row_data\\n\\n_U_s_a_g_e:\\n\\n     \\n         (\\n       object,\\n       screening_vars,\\n       distribution_vars,\\n       which_data\\n     )\\n     \\n_A_r_g_u_m_e_n_t_s:\\n\\n  object: An object of class metime_analyser\\n\\nscreening_vars: A character vector to define the vars that are to be\\n          updated as per add_screening_vars() else set it to\\n          NULL(Default).\\n\\ndistribution_vars: A character naming the vars of interest\\n\\nwhich_data: dataset to which the information is to be added(only 1 can\\n          be used at a time)\\n\\n_V_a_l_u_e:\\n\\n     object of class metime_analyser with phenotype data added to row\\n     data\\n\\n_S_e_e _A_l_s_o:\\n\\n     add_screening_vars\\n\\n_E_x_a_m_p_l_e_s:\\n\\n     object <- \\n         (object=data, screening_vars=c('var1', 'var2'), \\n                     distribution_vars=c('var1', 'var2', 'var3'), which_data='dataset1')\\n     ")
``` 

```{r ,echo=F}
bsplus::bs_modal(id = "15",title = "mod_merge_row_data_and_data",size = "large",body = "_M_o_d_i_f_i_c_a_t_i_o_n (_m_o_d) _f_u_n_c_t_i_o_n _t_o _m_e_r_g_e _d_a_t_a _a_n_d _r_o_w__d_a_t_a (_s_a_m_p_l_e _i_n_f_o)\\n_p_a_r_t_i_a_l_l_y _o_r _c_o_m_p_l_e_t_e_l_y.\\n\\n_D_e_s_c_r_i_p_t_i_o_n:\\n\\n     a modification function that merges partial or complete data and\\n     row_data of a dataset. If you want to use certain columns for the\\n     rest of the analysis properly for annotating plots then use\\n     mod_mutate function to rename the colnames and rownames (if\\n     applicable) to maintain consistency in the merged dataset\\n\\n_U_s_a_g_e:\\n\\n     \\n         (\\n       object,\\n       which_data,\\n       cols_list = list(data = NULL, row_data = NULL),\\n       append = FALSE,\\n       name = 'merged_data'\\n     )\\n     \\n_A_r_g_u_m_e_n_t_s:\\n\\n  object: an S4 object of class metime_analyser.\\n\\nwhich_data: a character defining which data and row_data should be\\n          merged. Has to contain only one value.\\n\\ncols_list: A list of named character vectors to merge dataset. example:\\n          which_data = 'dataset1'; cols_list = list(data=c(...),\\n          row_data=c(...)) or list(c(...), c(...)) If you want full\\n          data set cols_list=list(data=NULL, row_data=NULL) which is\\n          the default setting\\n\\n    name: a character to define the name of a new dataset.\\n\\n_V_a_l_u_e:\\n\\n     a new S4 object of class metime_analyser with the new merged\\n     dataset appended to it\\n\\n_S_e_e _A_l_s_o:\\n\\n     mod_merge_results, mod_merge_data\\n")
``` 

```{r ,echo=F}
bsplus::bs_modal(id = "16",title = "mod_mutate",size = "large",body = "_F_u_n_c_t_i_o_n _t_o _m_u_t_a_t_e _c_o_l_u_m_n_s _i_n _r_o_w__d_a_t_a _o_r _c_o_l__d_a_t_a\\n\\n_D_e_s_c_r_i_p_t_i_o_n:\\n\\n     Modification(mod) function to mutate data, row_data, col_data and\\n     results. It is a wrapper function to dplyr::mutate() made for\\n     metime_analyser objects.\\n\\n_U_s_a_g_e:\\n\\n     \\n         (object, which_data, type = 'data', ...)\\n     \\n_A_r_g_u_m_e_n_t_s:\\n\\n  object: An S4 object of class metime_analyser\\n\\nwhich_data: character or numeric input to define Dataset/result of\\n          interest. Has to be of length=1\\n\\n    type: character input of length 1 to define the type of data to be\\n          manipulated. Accepted inputs are 'row_data', 'col_data',\\n          'data' and 'results'. However renamed results will be\\n          returned to the user as a list of results and will not return\\n          the full analyser object\\n\\n     ...: arguments to pass directly into dplyr::mutate() function.\\n\\n_V_a_l_u_e:\\n\\n     object with mutated data\\n\\n_S_e_e _A_l_s_o:\\n\\n     mod_filter, mod_rename\\n")
``` 

```{r ,echo=F}
bsplus::bs_modal(id = "17",title = "calc_ggm_genenet",size = "large",body = "_A_n _a_u_t_o_m_a_t_e_d _f_u_c_n_t_i_o_n _t_o _c_a_l_c_u_l_a_t_e _G_G_M _f_r_o_m _g_e_n_e_n_e_t _c_r_o_s_s_s_e_c_t_i_o_n_a_l\\n_v_e_r_s_i_o_n\\n\\n_D_e_s_c_r_i_p_t_i_o_n:\\n\\n     automated funtion that can be applied on metime_analyser object to\\n     obtain geneNet network along with threshold used\\n\\n_U_s_a_g_e:\\n\\n     \\n         (\\n       object,\\n       which_data,\\n       threshold,\\n       all,\\n       cols_for_meta,\\n       covariates,\\n       stratifications,\\n       name,\\n       ...\\n     )\\n     \\n_A_r_g_u_m_e_n_t_s:\\n\\n  object: S4 object of cĺass metime_analyser\\n\\nwhich_data: a character or a character vector naming the datasets of\\n          interest\\n\\nthreshold: type of threshold to be used for extracting significant\\n          edges. allowed inputs are 'li', 'FDR', 'bonferroni'\\n\\n     all: Logical to extract all edges without any pval correction\\n\\ncols_for_meta: list of character vector for extracting metadata of\\n          metabolites for plotting\\n\\ncovariates: covariates to be used for this analysis\\n\\nstratifications: List to stratify data into a subset. Usage\\n          list(name=value)\\n\\n    name: Name of the result\\n\\n     ...: additional arguments for GeneNet\\n\\n_V_a_l_u_e:\\n\\n     Network data as a plotter object\\n")
``` 


## Plots{.tabset}


### network


GeneNet GGM results for: ggm_data with c("t0", "t12", "t24")


```{r,echo=F, warning=FALSE, message=FALSE}

plot_obj <- 
results_list[[1]][[1]]$items[[1]]$plots


if (inherits(plot_obj, "htmlwidget")) {

  plot_obj

} else if (is.list(plot_obj) && length(plot_obj) == 1 && inherits(plot_obj[[1]], "htmlwidget")) {

  plot_obj[[1]]

} else {

  plot_obj

}


```

# Session info
```{r session_info,include=T, warning=FALSE, message=FALSE}
print(sessionInfo())
```

