usethis::use_package("tidyverse", type="depends")
usethis::use_package("igraph", type="depends")
usethis::use_package("plyr", type="depends")
usethis::use_package("DT", type="depends")
usethis::use_package("M3C", type="depends")
usethis::use_package("umap", type="depends")
usethis::use_package("ggplot2", type="depends")
usethis::use_package("plotly", type="depends")
usethis::use_package("RColorBrewer", type="depends")
usethis::use_package("GeneNet", type="depends")
usethis::use_package("longitudinal", type="depends")
usethis::use_package("glmnet", type="depends")
usethis::use_package("Boruta", type="depends")

